# Generated by Django 5.1.1 on 2024-11-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_colecao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecao',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
